### ISSUE TITLE
Enderlings spawn out of control due to an unfortunate choice of event subscription.

### ISSUE THREAD

**Issue by D0CTOR-ZED** [wildcardgamez/BuddyCards#15]
As noted here, https://github.com/Engineers-Life/EL2/issues/86 , the Enderling spawn rate is out of control.

The source here, https://github.com/wildcardgamez/BuddyCards/blob/a011fcc8877f42169f355c28db8908a7d5b7bd75/src/main/java/com/wildcard/buddycards/util/EntitySpawning.java#L12 , shows that the event subscribed to is LivingSpawnEvent.

LivingSpawnEvent event includes CheckSpawn, SpecialSpawn, and AllowDespawn.  My understand of AllowDespawn is that it fires every tick to determine if the mob should despawn.  Therefore, Enderlings would check their chance to spawn every tick for every enderman.  I think you probably want SpecialSpawn, but this is a bit outside my area of experience.

**Comment by wildcardgamez** [comment]
As for that last section, it only checks their chance to spawn on the first tick of an enderman being spawned in, but nonetheless this is a serious bug and will be patched asap. I assume this is because the chunk loading doesn't properly tick the endermen, but I only checked for spawning this way because I didn't know of an alternative way. Shouldn't take more than a day to fix and send out a patch. Sorry for the trouble!

**Comment by wildcardgamez** [comment]
lmk if it works so I can close this issue

**Comment by czbuendel** [comment]
It appears to have worked, Zed and me were able to replicate them duplicating. We updated the mod and it appears all good now. Got a few to spawn after the update so all seems good.
![2021-05-20_23 01 52](https://user-images.githubusercontent.com/23238026/119080674-23c67480-b9c0-11eb-87d5-8733f451c7e3.png)
They are super cute.

**Comment by D0CTOR-ZED** [comment]
That little backpack is awesome.  Thanks for making such a unique mod.  Also, thanks for the quick response addressing the issue.
