### ISSUE TITLE
Opening a Farmer's Delight Buddycard Pack results into crashing the game.

### ISSUE THREAD

**Issue by Spider301** [wildcardgamez/BuddyCards#27]
When I try to open this type of pack, the game makes all the IA freeze and when you mine a block, it doesn't give you the drop. When you try to exit the game, it gets stuck in "Saving World", the only way to exit from here is  killing the process throught the Task Manager. 

The modpack that I use: 

Buddycards: V 2.5.0 
Farmer's Delight: V 0.4.5
Aquaculture: V 2.1.19

[latest.log](https://github.com/wildcardgamez/BuddyCards/files/6790730/latest.log)

**Comment by wildcardgamez** [comment]
Fixed for 1.17.1-2.6.0
https://github.com/wildcardgamez/BuddyCards/commit/4326d8601435b2275cbf9b985fbc35e7939af834

**Comment by ThomasElvangMoeller** [comment]
Will there also be a fix for 1.16? Most of my mods have not updated yet, like Create and farmer's delight

**Comment by wildcardgamez** [comment]
Probably not, my suggestion would just be to disable the recipe. While this isn't at all a fix, nor is it an excuse, I don't plan on working on both versions of the mod at once, it'd just be a bit chaotic for me. I might be able to depending on how my workspace is setup, but as of right now I don't have a lot of time to work on the mod, I was only able to get it to 1.17 because I had a week-long break. I'll see what I can do and if I go back and do some form of 1.16.5 patch I'll put it here

**Comment by barkerm1031** [comment]
I apologize for bumping this closed post. i was having this same issue and have a feeling it is just a mix up in the coding as the Mystery pack does infact succeed in the operation for the random gummy card. Would there be anyway you wouldnt mind if i could get the src for the 1.16.5 version of the mod to look at it? only reason im asking is due to your previous statement on this post.

**Comment by wildcardgamez** [comment]
the reason is in mystery packs it doesn't care about gummy cards in the same way farmers delight packs do, and all the code is here on github, if you want to see 1.16.5 code though, you have to go through history. This is one reason I don't support older versions, I don't keep a branch for each version

**Comment by barkerm1031** [comment]
gotcha ill look for it. and that does make sense. thanks for the reply!
